onEvent('recipes', event => {
    
    // Basalt
    event.shapeless('1x compressium:basalt_1', '9x minecraft:basalt')
    event.shapeless('1x compressium:basalt_2', '9x compressium:basalt_1')
    event.shapeless('1x compressium:basalt_3', '9x compressium:basalt_2')
    event.shapeless('1x compressium:basalt_4', '9x compressium:basalt_3')
    event.shapeless('1x compressium:basalt_5', '9x compressium:basalt_4')
    event.shapeless('1x compressium:basalt_6', '9x compressium:basalt_5')
    event.shapeless('1x compressium:basalt_7', '9x compressium:basalt_6')
    event.shapeless('1x compressium:basalt_8', '9x compressium:basalt_7')
    event.shapeless('1x compressium:basalt_9', '9x compressium:basalt_8')
  
    event.shapeless('9x compressium:basalt_8', '1x compressium:basalt_9')
    event.shapeless('9x compressium:basalt_7', '1x compressium:basalt_8')
    event.shapeless('9x compressium:basalt_6', '1x compressium:basalt_7')
    event.shapeless('9x compressium:basalt_5', '1x compressium:basalt_6')
    event.shapeless('9x compressium:basalt_4', '1x compressium:basalt_5')
    event.shapeless('9x compressium:basalt_3', '1x compressium:basalt_4')
    event.shapeless('9x compressium:basalt_2', '1x compressium:basalt_3')
    event.shapeless('9x compressium:basalt_1', '1x compressium:basalt_2')
    event.shapeless('9x minecraft:basalt', '1x compressium:basalt_1')
  
    // Blackstone
    event.shapeless('1x compressium:blackstone_1', '9x minecraft:blackstone')
    event.shapeless('1x compressium:blackstone_2', '9x compressium:blackstone_1')
    event.shapeless('1x compressium:blackstone_3', '9x compressium:blackstone_2')
    event.shapeless('1x compressium:blackstone_4', '9x compressium:blackstone_3')
    event.shapeless('1x compressium:blackstone_5', '9x compressium:blackstone_4')
    event.shapeless('1x compressium:blackstone_6', '9x compressium:blackstone_5')
    event.shapeless('1x compressium:blackstone_7', '9x compressium:blackstone_6')
    event.shapeless('1x compressium:blackstone_8', '9x compressium:blackstone_7')
    event.shapeless('1x compressium:blackstone_9', '9x compressium:blackstone_8')
  
    event.shapeless('9x compressium:blackstone_8', '1x compressium:blackstone_9')
    event.shapeless('9x compressium:blackstone_7', '1x compressium:blackstone_8')
    event.shapeless('9x compressium:blackstone_6', '1x compressium:blackstone_7')
    event.shapeless('9x compressium:blackstone_5', '1x compressium:blackstone_6')
    event.shapeless('9x compressium:blackstone_4', '1x compressium:blackstone_5')
    event.shapeless('9x compressium:blackstone_3', '1x compressium:blackstone_4')
    event.shapeless('9x compressium:blackstone_2', '1x compressium:blackstone_3')
    event.shapeless('9x compressium:blackstone_1', '1x compressium:blackstone_2')
    event.shapeless('9x minecraft:blackstone', '1x compressium:blackstone_1')
  
    // Deepslate
    event.shapeless('1x compressium:deepslate_1', '9x quark:deepslate')
    event.shapeless('1x compressium:deepslate_2', '9x compressium:deepslate_1')
    event.shapeless('1x compressium:deepslate_3', '9x compressium:deepslate_2')
    event.shapeless('1x compressium:deepslate_4', '9x compressium:deepslate_3')
    event.shapeless('1x compressium:deepslate_5', '9x compressium:deepslate_4')
    event.shapeless('1x compressium:deepslate_6', '9x compressium:deepslate_5')
    event.shapeless('1x compressium:deepslate_7', '9x compressium:deepslate_6')
    event.shapeless('1x compressium:deepslate_8', '9x compressium:deepslate_7')
    event.shapeless('1x compressium:deepslate_9', '9x compressium:deepslate_8')
  
    event.shapeless('9x compressium:deepslate_8', '1x compressium:deepslate_9')
    event.shapeless('9x compressium:deepslate_7', '1x compressium:deepslate_8')
    event.shapeless('9x compressium:deepslate_6', '1x compressium:deepslate_7')
    event.shapeless('9x compressium:deepslate_5', '1x compressium:deepslate_6')
    event.shapeless('9x compressium:deepslate_4', '1x compressium:deepslate_5')
    event.shapeless('9x compressium:deepslate_3', '1x compressium:deepslate_4')
    event.shapeless('9x compressium:deepslate_2', '1x compressium:deepslate_3')
    event.shapeless('9x compressium:deepslate_1', '1x compressium:deepslate_2')
    event.shapeless('9x quark:deepslate', '1x compressium:deepslate_1')
  
    // Cobbled Deepslate
    event.shapeless('1x compressium:cobbled_deepslate_1', '9x quark:cobbled_deepslate')
    event.shapeless('1x compressium:cobbled_deepslate_2', '9x compressium:cobbled_deepslate_1')
    event.shapeless('1x compressium:cobbled_deepslate_3', '9x compressium:cobbled_deepslate_2')
    event.shapeless('1x compressium:cobbled_deepslate_4', '9x compressium:cobbled_deepslate_3')
    event.shapeless('1x compressium:cobbled_deepslate_5', '9x compressium:cobbled_deepslate_4')
    event.shapeless('1x compressium:cobbled_deepslate_6', '9x compressium:cobbled_deepslate_5')
    event.shapeless('1x compressium:cobbled_deepslate_7', '9x compressium:cobbled_deepslate_6')
    event.shapeless('1x compressium:cobbled_deepslate_8', '9x compressium:cobbled_deepslate_7')
    event.shapeless('1x compressium:cobbled_deepslate_9', '9x compressium:cobbled_deepslate_8')
  
    event.shapeless('9x compressium:cobbled_deepslate_8', '1x compressium:cobbled_deepslate_9')
    event.shapeless('9x compressium:cobbled_deepslate_7', '1x compressium:cobbled_deepslate_8')
    event.shapeless('9x compressium:cobbled_deepslate_6', '1x compressium:cobbled_deepslate_7')
    event.shapeless('9x compressium:cobbled_deepslate_5', '1x compressium:cobbled_deepslate_6')
    event.shapeless('9x compressium:cobbled_deepslate_4', '1x compressium:cobbled_deepslate_5')
    event.shapeless('9x compressium:cobbled_deepslate_3', '1x compressium:cobbled_deepslate_4')
    event.shapeless('9x compressium:cobbled_deepslate_2', '1x compressium:cobbled_deepslate_3')
    event.shapeless('9x compressium:cobbled_deepslate_1', '1x compressium:cobbled_deepslate_2')
    event.shapeless('9x quark:cobbled_deepslate', '1x compressium:cobbled_deepslate_1')
    
  })