console.info('Adding Unobtanium!')


onEvent('block.registry', event => {

	event.create('architects_palette:unobtanium_block').displayName('Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:white_unobtanium_block').displayName('White Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:orange_unobtanium_block').displayName('Orange Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:magenta_unobtanium_block').displayName('Magenta Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:light_blue_unobtanium_block').displayName('Light Blue Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:yellow_unobtanium_block').displayName('Yellow Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:lime_unobtanium_block').displayName('Lime Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:pink_unobtanium_block').displayName('Pink Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:gray_unobtanium_block').displayName('Gray Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:light_gray_unobtanium_block').displayName('Light Gray Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:cyan_unobtanium_block').displayName('Cyan Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:blue_unobtanium_block').displayName('Blue Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:brown_unobtanium_block').displayName('Brown Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:green_unobtanium_block').displayName('Green Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:red_unobtanium_block').displayName('Red Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:purple_unobtanium_block').displayName('Purple Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 
	event.create('architects_palette:black_unobtanium_block').displayName('Black Unobtanium Block').material('lantern').hardness(7.0).harvestTool('pickaxe', 0) 

})

onEvent('item.registry', event => {
	event.create('architects_palette:unobtanium').displayName('Unobtanium')
	event.create('architects_palette:white_unobtanium').displayName('White Unobtanium')
	event.create('architects_palette:orange_unobtanium').displayName('Orange Unobtanium')
	event.create('architects_palette:magenta_unobtanium').displayName('Magenta Unobtanium')
	event.create('architects_palette:light_blue_unobtanium').displayName('Light Blue Unobtanium')
	event.create('architects_palette:yellow_unobtanium').displayName('Yellow Unobtanium')
	event.create('architects_palette:lime_unobtanium').displayName('Lime Unobtanium')
	event.create('architects_palette:pink_unobtanium').displayName('Pink Unobtanium')
	event.create('architects_palette:gray_unobtanium').displayName('Gray Unobtanium')
	event.create('architects_palette:light_gray_unobtanium').displayName('Light Gray Unobtanium')
	event.create('architects_palette:cyan_unobtanium').displayName('Cyan Unobtanium')
	event.create('architects_palette:blue_unobtanium').displayName('Blue Unobtanium')
	event.create('architects_palette:brown_unobtanium').displayName('Brown Unobtanium')
	event.create('architects_palette:green_unobtanium').displayName('Green Unobtanium')
	event.create('architects_palette:red_unobtanium').displayName('Red Unobtanium')
	event.create('architects_palette:purple_unobtanium').displayName('Purple Unobtanium')
	event.create('architects_palette:black_unobtanium').displayName('Black Unobtanium')
})