console.info("Removing & Adding JEI entries!")

onEvent('jei.add.items', event => {
	event.add(Item.of('the_vault:reset_flask', '{Skillable:"Artisan"}'))
	event.add(Item.of('the_vault:reset_flask', '{Skillable:"Treasure Hunter"}'))
	event.add(Item.of('appliedenergistics2:facade', '{item:"minecraft:stone"}'))
})

onEvent('jei.hide.items', event => {
	event.hide(Item.of('mekanism:mekasuit_helmet', {HideFlags:2}))
	event.hide(Item.of('mekanism:mekasuit_bodyarmor', {HideFlags:2}))
	event.hide(Item.of('mekanism:mekasuit_pants', {HideFlags:2}))
	event.hide(Item.of('mekanism:mekasuit_boots', {HideFlags:2}))
	event.hide(Item.of('mekanism:meka_tool', {HideFlags:2}))
	event.hide('mekanism:module_laser_dissipation_unit')
	event.hide('mekanism:module_radiation_shielding_unit')
	event.hide('mekanism:module_solar_recharging_unit')
	event.hide('mekanism:module_jetpack_unit')
	event.hide('mekanism:module_charge_distribution_unit')
	event.hide('mekanism:module_elytra_unit')
	event.hide('botania:dice')
	event.hide('botania:thor_ring')
	event.hide('botania:loki_ring')
	event.hide('botania:odin_ring')
	event.hide('botania:flugel_eye')
	event.hide('botania:king_key')
	event.hide('botania:infinite_fruit')
	event.hide('botania:balance_cloak')
	event.hide('botania:holy_cloak')
	event.hide('botania:unholy_cloak')
	event.hide('botania:star_sword')
	event.hide('botania:thunder_sword')
	event.hide('botania:ender_hand')
	event.hide('botania:dice')
	event.hide('botania:terrasteel_helmet')
	event.hide('botania:terrasteel_chestplate')
	event.hide('botania:terrasteel_leggings')
	event.hide('botania:terrasteel_boots')
	event.hide('botania:manasteel_helmet')
	event.hide('botania:manasteel_chestplate')
	event.hide('botania:manasteel_leggings')
	event.hide('botania:manasteel_boots')
	event.hide('botania:elementium_helmet')
	event.hide('botania:elementium_chestplate')
	event.hide('botania:elementium_leggings')
	event.hide('botania:elementium_boots')
	event.hide('botania:manaweave_helmet')
	event.hide('botania:manaweave_chestplate')
	event.hide('botania:manaweave_leggings')
	event.hide('botania:manaweave_boots')
	event.hide('botania:terra_axe')
	event.hide('botania:terra_sword')
	event.hide('botania:elementium_pickaxe')
	event.hide('botania:elementium_shovel')
	event.hide('botania:elementium_hoe')
	event.hide('botania:elementium_axe')
	event.hide('botania:elementium_sword')
	event.hide('botania:elementium_shears')
	event.hide('botania:manasteel_pick')
	event.hide('botania:manasteel_shovel')
	event.hide('botania:manasteel_hoe')
	event.hide('botania:manasteel_axe')
	event.hide('botania:manasteel_sword')
	event.hide('botania:manasteel_shears')
	event.hide('the_vault:puzzle_rune')
	event.hide('the_vault:puzzle_rune_block')
	event.hide('the_vault:ore_unknown')
	event.hide('the_vault:door_iskallium')
	event.hide('the_vault:door_puffium')
	event.hide('the_vault:door_gorginite')
	event.hide('the_vault:door_sparkletine')
	event.hide('the_vault:door_ashium')
	event.hide('the_vault:door_funsoide')
	event.hide('the_vault:door_unknown')
	event.hide('the_vault:door_bomignite')
	event.hide('the_vault:door_upaline')
	event.hide('the_vault:door_tubium')
	event.hide('the_vault:vault_chest')
	event.hide('the_vault:vault_richity')
	event.hide('the_vault:vault_resource')
	event.hide('the_vault:vault_misc')
	event.hide('the_vault:vault_treasure_chest')
	event.hide('the_vault:vault_altar_chest')
	event.hide('the_vault:vault_rune')
	event.hide('industrialforegoing:mob_duplicator')
	event.hide('ironjetpacks:emerald_jetpack')
	event.hide('quark:matrix_enchanter')
	event.hide('enchantinginfuser:advanced_enchanting_infuser')
	event.hide('quark:blossom_planks')
	event.hide('quark:blossom_boards')
	event.hide(Item.of('appliedenergistics2:facade').ignoreNBT())

})